### ISSUE TITLE
Testes

### ISSUE THREAD

**Issue by mrprompt** [clebersonmachi/BoletoSicoob#2]
Adicionar testes unitários.

**Comment by clebersonmachi** [comment]
Adicionei os teste unitários, muito obrigado pelas sugestões...

**Comment by mrprompt** [comment]
Show valeu! Agora só precisa trocar o Travis pra pegar daqui e não do meu fork.

**Comment by clebersonmachi** [comment]
Desculpa, mas eu nunca usei nenhuma ferramenta de testes, não sei como fazer isto.
Se puder me auxiliar como se faz isto eu ficaria muito grato.

Desde já agradeço a ajuda

**Comment by mrprompt** [comment]
Ajudo com o maior prazer:
- vá em http://travis-ci.org e se cadastra (só se logar com teu github)
- dá uma olhada aqui pra conhecer: https://ci.mrprompt.com.br/capitulo-2/
- a configuração já tá pronta, é só vincular esse repositório a tua conta, e atualizar o README.md trocando o meu user pro teu.
